seed: 0
num_workers: 4

train:
  batch_size: 8
  num_epochs: 3
  steps_per_epoch: 5

test:
  batch_size: 8
  steps_per_epoch: 5

dataset:
  name: "cifar10"
  resolution: &resolution 32
  num_classes: &num_classes 10

model:
  resolution: *resolution
  in_channels: 3
  out_channels: *num_classes

optimizer:
  lr: 1.0e-3