seed: 0
num_workers: 4

train:
  batch_size: 128
  num_epochs: 1000
  steps_per_epoch: 100

test:
  batch_size: 128
  steps_per_epoch: 10

dataset:
  name: "cifar10"
  resolution: &resolution 32
  num_classes: &num_classes 10

model:
  resolution: *resolution
  in_channels: 3
  out_channels: *num_classes

optimizer:
  lr: 1.0e-3
  lr_warmup_steps: 1
