seed: 0
save_freq: 100
log_dir: null
num_workers: 4
compile: true

train:
  batch_size: 8
  num_epochs: 3
  steps_per_epoch: 5

test:
  enabled: True
  batch_size: 8
  steps_per_epoch: 5

dataset:
  name: "cifar10"
  resolution: &resolution 32
  num_classes: &num_classes 10

model:
  in_channels: 3
  out_channels: *num_classes

optim:
  lr: 1.0e-3
